// src/components/FilterEditor.vue
<template>
  <div class="filter-editor">
    <ConditionsEditor
      :conditions-tree="conditionsTree"
      @conditionsTreeUpdated="updateFilterTree"
      :defaultValue="defaultValue"
    >
      <template v-slot:default="slotProps">
        <FilterSimpleConditionWidget
          :value="slotProps.condition || undefined"
          @input="slotProps.updateCondition"
          :columnNamesProp="Object.keys(columnTypes)"
          :available-variables="availableVariables"
          :variable-delimiters="variableDelimiters"
          :hideColumnVariables="hideColumnVariables"
          :hideColumnInput="hideColumnInput"
          :data-path="slotProps.dataPath"
          :errors="errors"
          :multi-variable="multiVariable"
          :columnTypes="columnTypes"
        />
      </template>
    </ConditionsEditor>
  </div>
</template>

<script lang="ts">
import { ErrorObject } from 'ajv';
import { Component, Prop, Vue } from 'vue-property-decorator';

import ConditionsEditor from '@/components/ConditionsEditor/ConditionsEditor.vue';
import { AbstractFilterTree } from '@/components/ConditionsEditor/tree-types';
import {
  buildConditionsEditorTree,
  buildFilterStepTree,
  castFilterStepTreeValue,
} from '@/components/stepforms/convert-filter-step-tree.ts';
import FilterSimpleConditionWidget, {
  DEFAULT_FILTER,
} from '@/components/stepforms/widgets/FilterSimpleCondition.vue';
import { ColumnTypeMapping } from '@/lib/dataset/index.ts';
import { FilterCondition } from '@/lib/steps';
import { VariableDelimiters, VariablesBucket } from '@/lib/variables';

@Component({
  name: 'filter-editor',
  components: {
    ConditionsEditor,
    FilterSimpleConditionWidget,
  },
})
export default class FilterEditor extends Vue {
  @Prop({
    type: Object,
    default: () => ({ column: '', value: '', operator: 'eq' }),
  })
  filterTree!: FilterCondition;

  @Prop({
    type: Object,
    default: () => ({}),
  })
  columnTypes!: ColumnTypeMapping;

  @Prop()
  availableVariables?: VariablesBucket;

  @Prop()
  variableDelimiters?: VariableDelimiters;

  @Prop()
  hideColumnVariables?: boolean;

  @Prop({ type: Boolean, default: false })
  hideColumnInput!: boolean;

  @Prop({ type: Boolean, default: true })
  multiVariable!: boolean; // display multiInputText as multiVariableInput

  @Prop({
    type: Array,
    default: () => [],
  })
  errors!: ErrorObject[];

  readonly defaultValue = DEFAULT_FILTER;

  get conditionsTree() {
    return buildConditionsEditorTree(castFilterStepTreeValue(this.filterTree, this.columnTypes));
  }

  updateFilterTree(newConditionsTree: AbstractFilterTree) {
    const newFilterTree = buildFilterStepTree(newConditionsTree);
    this.$emit('filterTreeUpdated', newFilterTree);
  }
}
</script>

// next-ui/components/FilterEditor.tsx
import React, { useMemo } from 'react';
import { ErrorObject } from 'ajv';

import ConditionsEditor from '@/components/ConditionsEditor/ConditionsEditor';
import { AbstractFilterTree } from '@/components/ConditionsEditor/tree-types';
import {
  buildConditionsEditorTree,
  buildFilterStepTree,
  castFilterStepTreeValue,
} from '@/components/stepforms/convert-filter-step-tree';
import FilterSimpleConditionWidget, {
  DEFAULT_FILTER,
} from '@/components/stepforms/widgets/FilterSimpleCondition';
import { ColumnTypeMapping } from '@/lib/dataset';
import { FilterCondition, FilterSimpleCondition } from '@/lib/steps';
import { VariableDelimiters, VariablesBucket } from '@/lib/variables';

interface FilterEditorProps {
  filterTree?: FilterCondition;
  columnTypes?: ColumnTypeMapping;
  availableVariables?: VariablesBucket;
  variableDelimiters?: VariableDelimiters;
  trustedVariableDelimiters?: VariableDelimiters;
  hideColumnVariables?: boolean;
  multiVariable?: boolean;
  errors?: ErrorObject[];
  onFilterTreeUpdated: (newTree: FilterCondition) => void;
  onSetSelectColumns?: (columns: { column: string }) => void;
}

export default function FilterEditor({
  filterTree = { column: '', value: '', operator: 'eq' },
  columnTypes = {},
  availableVariables,
  variableDelimiters,
  trustedVariableDelimiters,
  hideColumnVariables,
  multiVariable = true,
  errors = [],
  onFilterTreeUpdated,
  onSetSelectColumns,
}: FilterEditorProps) {

  const defaultValue = DEFAULT_FILTER;

  const conditionsTree = useMemo(() => {
    return buildConditionsEditorTree(castFilterStepTreeValue(filterTree, columnTypes));
  }, [filterTree, columnTypes]);

  const updateFilterTree = (newConditionsTree: AbstractFilterTree) => {
    const newFilterTree = buildFilterStepTree(newConditionsTree);
    // Cast back to FilterCondition because buildFilterStepTree returns object
    onFilterTreeUpdated(newFilterTree as FilterCondition);
  };

  return (
    <div className="filter-editor">
      <ConditionsEditor
        conditionsTree={conditionsTree}
        onConditionsTreeUpdated={updateFilterTree}
        defaultValue={defaultValue}
        renderCondition={({ condition, updateCondition, dataPath }) => (
            <FilterSimpleConditionWidget
                value={condition || undefined}
                onChange={updateCondition}
                columnNamesProp={Object.keys(columnTypes)}
                availableVariables={availableVariables}
                variableDelimiters={variableDelimiters}
                trustedVariableDelimiters={trustedVariableDelimiters}
                hideColumnVariables={hideColumnVariables}
                dataPath={dataPath}
                errors={errors}
                multiVariable={multiVariable}
                columnTypes={columnTypes}
                onSetSelectedColumns={onSetSelectColumns}
            />
        )}
      />
    </div>
  );
}
