// next-ui/components/stepforms/widgets/InputDate.tsx
import React from 'react';
import classNames from 'classnames';

import FAIcon from '@/components/FAIcon';
import VariableInput from './VariableInput';
import { useFormWidget } from './FormWidget';
import Calendar from '@/components/DatePicker/Calendar';
import styles from './InputDate.module.scss'; // We need to create this
import formStyles from './FormWidget.module.scss';
import { DateRange } from '@/lib/dates';

import Popover from '@/components/Popover';
import { Alignment } from '@/components/constants';

interface InputDateProps {
  name?: string;
  placeholder?: string;
  value?: Date | string | number | DateRange; // Accept string/number for flexibility, DateRange if needed
  docUrl?: string;
  availableVariables?: any;
  variableDelimiters?: any;
  trustedVariableDelimiters?: any;
  dataPath?: string;
  errors?: any[];
  warning?: string;
  onChange: (val: any) => void;
  className?: string;
  // Extra props for Calendar if needed, though usually InputDate implies a single date or specific config
}

export default function InputDateWidget({
  name = '',
  placeholder = '',
  value,
  docUrl,
  availableVariables,
  variableDelimiters,
  trustedVariableDelimiters,
  dataPath,
  errors,
  warning,
  onChange,
  className
}: InputDateProps) {

  const { messageError, messageWarning, toggleClassErrorWarning } = useFormWidget({ dataPath, errors, warning });

  const [isOpen, setIsOpen] = React.useState(false);

  // Value formatting for display
  const displayValue = value instanceof Date ? value.toLocaleDateString() : String(value || '');

  const handleDateSelect = (date: Date | DateRange | undefined) => {
      onChange(date);
      setIsOpen(false);
  };

  return (
    <div className={classNames(styles['widget-input-date__container'], toggleClassErrorWarning, className)}>
       <div className={styles['widget-input-date__label-container']}>
            {name && <label>{name}</label>}
       </div>

       <div className={styles['widget-input-date__input-wrapper']}>
           <input
              className={styles['widget-input-date__input']}
              value={displayValue}
              placeholder={placeholder}
              readOnly
              onClick={() => setIsOpen(true)}
           />

           <Popover
              visible={isOpen}
              align={Alignment.Left}
              onClosed={() => setIsOpen(false)}
              bottom
           >
              <Calendar
                  value={value instanceof Date ? value : undefined}
                  onInput={handleDateSelect}
              />
           </Popover>
       </div>

       {messageError && (
        <div className={formStyles['field__msg-error']}>
          <FAIcon icon="exclamation-circle" />
          {messageError}
        </div>
      )}
    </div>
  );
}

// ui/src/components/stepforms/widgets/InputDate.vue
<template>
  <div class="widget-input-date__container" :class="toggleClassErrorWarning">
    <div class="widget-input-date__label">
      <label v-if="name" @click="$refs.input.focus()">{{ name }}</label>
      <a v-if="docUrl" :href="docUrl" target="_blank" rel="noopener">
        <FAIcon class="widget-input-date__doc-icon" icon="question-circle" />
      </a>
    </div>
    <VariableInput
      :value="parsedValue"
      :available-variables="availableVariables"
      :variable-delimiters="variableDelimiters"
      :has-arrow="true"
      @input="updateValue"
    >
      <input
        ref="input"
        class="widget-input-date"
        :placeholder="placeholder"
        type="date"
        :value="parsedValue"
        @input="updateValue($event.target.value)"
      />
    </VariableInput>
    <div v-if="messageError" class="field__msg-error">
      <FAIcon icon="exclamation-circle" />
      {{ messageError }}
    </div>
    <div v-if="messageWarning" class="field__msg-warning">
      <FAIcon icon="exclamation-triangle" />
      {{ messageWarning }}
    </div>
  </div>
</template>

<script lang="ts">
import { Component, Prop } from 'vue-property-decorator';

import FAIcon from '@/components/FAIcon.vue';
import type { VariableDelimiters, VariablesBucket } from '@/lib/variables';

import FormWidget from './FormWidget.vue';
import VariableInput from './VariableInput.vue';

@Component({
  name: 'input-date-widget',
  components: {
    VariableInput,
    FAIcon,
  },
})
export default class InputDateWidget extends FormWidget {
  @Prop({ type: String, default: '' })
  name!: string;

  @Prop({ type: String, default: '' })
  placeholder!: string;

  @Prop({ default: '' })
  value!: string | Date;

  @Prop({ default: undefined })
  docUrl!: string | undefined;

  @Prop()
  availableVariables?: VariablesBucket;

  @Prop()
  variableDelimiters?: VariableDelimiters;

  get parsedValue(): string {
    return this.value instanceof Date ? this.parseDateToString(this.value) : this.value;
  }

  parseDateToString(date: Date): string {
    // transform a date to the expected date input string with format (YYYY-MM-DD)
    return date.toISOString().substr(0, 10);
  }

  updateValue(newValue: string): void {
    this.$emit('input', newValue);
  }
}
</script>

<style lang="scss" scoped>
@import '../../../styles/_variables';

.widget-input-date__container {
  @extend %form-widget__container;
}

.widget-input-date {
  @extend %form-widget__field;

  &:focus-within {
    @extend %form-widget__field--focused;
  }
}

.widget-input-date__label {
  align-items: flex-start;
  display: flex;
  justify-content: space-between;
  width: 100%;
}

.widget-input-date__label label {
  @extend %form-widget__label;
}

.widget-input-date__doc-icon {
  margin-left: 5px;
  color: $base-color;
  font-size: 14px;

  &:hover {
    color: $active-color;
  }
}
</style>
