// src/components/stepforms/widgets/FilterSimpleCondition.vue
<template>
  <div class="filter-form-simple-condition__container">
    <div
      class="filter-form-simple-condition-column-input"
      data-cy="weaverbird-filter-form-column-input"
    >
      <AutocompleteWidget
        class="columnInput"
        :value="value.column"
        :available-variables="hideColumnVariables ? undefined : availableVariables"
        :variable-delimiters="hideColumnVariables ? undefined : variableDelimiters"
        :options="columnNames"
        @input="updateStepColumn"
        placeholder="Column"
        :data-path="`${dataPath}.column`"
        :errors="errors"
      />
    </div>
    <div
      class="filter-form-simple-condition-operator-input"
      data-cy="weaverbird-filter-form-operator-input"
    >
      <AutocompleteWidget
        class="filterOperator"
        :value="operator"
        @input="updateStepOperator"
        :options="availableOperators"
        placeholder="Filter operator"
        :trackBy="`operator`"
        :label="`label`"
      />
    </div>
    <component
      class="filterValue"
      data-cy="weaverbird-filter-form-filter-value"
      v-if="inputWidget"
      :is="inputWidget"
      :multi-variable="multiVariable"
      :value="value.value"
      :available-variables="availableVariablesForInputWidget"
      :variable-delimiters="variableDelimiters"
      :placeholder="placeholder"
      :data-path="`${dataPath}.value`"
      :errors="errors"
      @input="updateStepValue"
    />
  </div>
</template>

<script lang="ts">
import { ErrorObject } from 'ajv';
import isEqual from 'lodash/isEqual';
import { VueConstructor } from 'vue';
import { Component, Prop, Vue, Watch } from 'vue-property-decorator';

import AutocompleteWidget from '@/components/stepforms/widgets/Autocomplete.vue';
import NewDateInput from '@/components/stepforms/widgets/DateComponents/NewDateInput.vue';
import InputTextWidget from '@/components/stepforms/widgets/InputText.vue';
import { ColumnTypeMapping } from '@/lib/dataset/index';
import {
  keepCurrentValueIfArrayType,
  keepCurrentValueIfCompatibleDate,
  keepCurrentValueIfCompatibleType,
} from '@/lib/helpers';
import { FilterSimpleCondition } from '@/lib/steps';
import { VariableDelimiters, VariablesBucket } from '@/lib/variables';
import { VQBModule } from '@/store';
import { MutationCallbacks } from '@/store/mutations';

import InputDateWidget from './InputDate.vue';
import MultiInputTextWidget from './MultiInputText.vue';

type LiteralOperator =
  | 'equals'
  | "doesn't equal"
  | 'is greater than'
  | 'is greater than or equal to'
  | 'is less than'
  | 'is less than or equal to'
  | 'is one of'
  | 'is not one of'
  | 'matches pattern'
  | "doesn't match pattern"
  | 'is null'
  | 'is not null'
  | 'from'
  | 'until';

type ShortOperator = FilterSimpleCondition['operator'];

type OperatorOption = {
  operator: ShortOperator;
  label: LiteralOperator;
  inputWidget?: VueConstructor<Vue>;
};

export const DEFAULT_FILTER = { column: '', value: '', operator: 'eq' };

@Component({
  name: 'filter-simple-condition-widget',
  components: {
    AutocompleteWidget,
    InputTextWidget,
    InputDateWidget,
    NewDateInput,
  },
})
export default class FilterSimpleConditionWidget extends Vue {
  @Prop({
    type: Object,
    default: () => ({ ...DEFAULT_FILTER }),
  })
  value!: FilterSimpleCondition;

  @Prop({
    type: Array,
    default: () => [],
  })
  columnNamesProp!: string[];

  @Prop({ type: String, default: '' })
  dataPath!: string;

  @Prop({ type: Array, default: () => [] })
  errors!: ErrorObject[];

  @Prop({ type: Boolean, default: true })
  multiVariable!: boolean; // display multiInputText as multiVariableInput

  @Prop({
    type: Object,
    default: () => ({}),
  })
  columnTypes!: ColumnTypeMapping;

  @VQBModule.Getter('columnNames') columnNamesFromStore!: string[];

  @VQBModule.State('featureFlags') featureFlags!: Record<string, any>;

  @VQBModule.Mutation setSelectedColumns!: MutationCallbacks['setSelectedColumns'];

  @Prop()
  availableVariables?: VariablesBucket;

  @Prop()
  variableDelimiters?: VariableDelimiters;

  @Prop()
  hideColumnVariables?: boolean;

  @Watch('hasDateSelectedColumn')
  verifyIfValueIsStillValid() {
    // when column change from date to another type or inverse,
    // we need to reapply default widget value in case current value is not valid
    // ex: [X] '' in string column will become an 'Invalid Date' in date column
    // ex: [X] new Date() in date column will become an object in string column
    this.updateStepOperator(this.operator);
  }

  readonly nullOperators: OperatorOption[] = [
    { operator: 'isnull', label: 'is null' },
    { operator: 'notnull', label: 'is not null' },
  ];

  readonly baseOperators: OperatorOption[] = [
    { operator: 'eq', label: 'equals', inputWidget: InputTextWidget },
    { operator: 'ne', label: "doesn't equal", inputWidget: InputTextWidget },
    { operator: 'gt', label: 'is greater than', inputWidget: InputTextWidget },
    { operator: 'ge', label: 'is greater than or equal to', inputWidget: InputTextWidget },
    { operator: 'lt', label: 'is less than', inputWidget: InputTextWidget },
    { operator: 'le', label: 'is less than or equal to', inputWidget: InputTextWidget },
    { operator: 'in', label: 'is one of', inputWidget: MultiInputTextWidget },
    { operator: 'nin', label: 'is not one of', inputWidget: MultiInputTextWidget },
    { operator: 'matches', label: 'matches pattern', inputWidget: InputTextWidget },
    { operator: 'notmatches', label: "doesn't match pattern", inputWidget: InputTextWidget },
    ...this.nullOperators,
  ];

  readonly dateOperators: OperatorOption[] = [
    { operator: 'from', label: 'from', inputWidget: NewDateInput },
    { operator: 'until', label: 'until', inputWidget: NewDateInput },
    ...this.nullOperators,
  ];

  created() {
    // In absence of condition, emit directly to the parent the default value
    if (isEqual(this.value, DEFAULT_FILTER)) {
      this.$emit('input', DEFAULT_FILTER);
    }
  }

  // Column names can be provided either in the store or via a prop
  // The prop takes priority over the store
  get columnNames() {
    if (this.columnNamesProp && this.columnNamesProp.length > 0) {
      return this.columnNamesProp;
    } else if (this.columnNamesFromStore && this.columnNamesFromStore.length > 0) {
      return this.columnNamesFromStore;
    } else {
      return [];
    }
  }

  get enableRelativeDateFiltering(): boolean {
    return this.featureFlags?.RELATIVE_DATE_FILTERING === 'enable';
  }

  get dateAvailableVariables(): VariablesBucket | undefined {
    // keep only date variables
    return this.availableVariables?.filter(v => v.value instanceof Date);
  }

  get availableVariablesForInputWidget(): VariablesBucket | undefined {
    switch (this.inputWidget) {
      case NewDateInput:
        return this.dateAvailableVariables;
      default:
        return this.availableVariables;
    }
  }

  get availableOperators(): OperatorOption[] {
    if (this.hasDateSelectedColumn && this.enableRelativeDateFiltering) {
      return this.dateOperators;
    }
    return this.baseOperators;
  }

  get placeholder() {
    if (this.value.operator === 'matches' || this.value.operator === 'notmatches') {
      return 'Enter a regex, e.g. "[Ss]ales"';
    }
    return 'Enter a value';
  }

  get hasDateSelectedColumn(): boolean {
    return this.columnTypes[this.value.column] == 'date';
  }

  get operator(): OperatorOption {
    return (
      this.availableOperators.find(d => d.operator === this.value.operator) ??
      this.availableOperators[0]
    );
  }

  get inputWidget(): VueConstructor<Vue> | undefined {
    const widget = this.operator.inputWidget;
    if (
      this.hasDateSelectedColumn &&
      widget === InputTextWidget &&
      !this.enableRelativeDateFiltering
    ) {
      return InputDateWidget;
    }
    return widget;
  }

  updateStepOperator(newOperator: OperatorOption) {
    const updatedValue = { ...this.value };
    updatedValue.operator = newOperator.operator;
    if (updatedValue.operator === 'in' || updatedValue.operator === 'nin') {
      updatedValue.value = keepCurrentValueIfArrayType(updatedValue.value, []);
    } else if (updatedValue.operator === 'isnull' || updatedValue.operator === 'notnull') {
      updatedValue.value = null;
    } else if (this.hasDateSelectedColumn) {
      // when using date widget, we need value to be a valid date
      // null as date will become "01/01/1970" as default value for input
      updatedValue.value = keepCurrentValueIfCompatibleDate(updatedValue.value, null);
    } else {
      updatedValue.value = keepCurrentValueIfCompatibleType(updatedValue.value, '');
    }
    this.$emit('input', updatedValue);
  }

  updateStepValue(newColumn: any) {
    const updatedValue = { ...this.value };
    updatedValue.value = newColumn;
    this.$emit('input', updatedValue);
  }

  updateStepColumn(newValue: string) {
    const updatedValue = { ...this.value };
    updatedValue.column = newValue;
    this.setSelectedColumns({ column: updatedValue.column });
    this.$emit('input', updatedValue);
  }
}
</script>
<style lang="scss" scoped>
.filter-form-simple-condition__container {
  display: flex;
  width: 100%;
}

.widget-autocomplete__container,
.widget-input-date__container,
.widget-input-text__container {
  margin: 0;
}

.filter-form-simple-condition-column-input,
.filter-form-simple-condition-operator-input,
.filter-form-simple-condition__container .widget-input-text__container,
.filter-form-simple-condition__container .widget-input-date__container,
.filter-form-simple-condition__container .widget-date-input,
.filter-form-simple-condition__container .widget-multiinputtext__container {
  margin: 4px;
  margin-right: 0;
  width: 33%;

  &:last-child {
    margin-right: 4px;
  }
}

.filter-form-simple-condition__container ::v-deep .widget-input-text,
.filter-form-simple-condition__container ::v-deep .widget-input-date,
.filter-form-simple-condition__container ::v-deep .widget-date-input__container,
.filter-form-simple-condition__container ::v-deep .multiselect {
  background-color: white;

  &::placeholder {
    font-size: 14px;
    letter-spacing: 1px;
  }
}

.filter-form-simple-condition__container ::v-deep .multiselect__tags {
  border-radius: 0;
  border: none;
}
</style>

<style lang="scss">
.filter-form-simple-condition__container .multiselect {
  width: 100%;
}
</style>

// next-ui/components/stepforms/widgets/FilterSimpleCondition.tsx
import React, { useMemo, useEffect, useRef } from 'react';
import isEqual from 'lodash/isEqual';
import classNames from 'classnames';

import { ColumnTypeMapping } from '@/lib/dataset';
import { FilterSimpleCondition } from '@/lib/steps';
import { VariablesBucket, VariableDelimiters } from '@/lib/variables';
import {
  keepCurrentValueIfArrayType,
  keepCurrentValueIfCompatibleRelativeDate,
  keepCurrentValueIfCompatibleType,
} from '@/lib/helpers';

// Use real components now
import AutocompleteWidget from './Autocomplete';
import InputTextWidget from './InputText';
import InputDateWidget from './InputDate';
import MultiInputTextWidget from './MultiInputText';

// Still placeholders for these for now
const NewDateInput = (props: any) => <InputDateWidget {...props} />; // Map to InputDateWidget

import styles from './FilterSimpleCondition.module.scss';

type LiteralOperator =
  | 'equals'
  | "doesn't equal"
  | 'is greater than'
  | 'is greater than or equal to'
  | 'is less than'
  | 'is less than or equal to'
  | 'is one of'
  | 'is not one of'
  | 'matches pattern'
  | "doesn't match pattern"
  | 'is null'
  | 'is not null'
  | 'starting in/on'
  | 'ending in/on';

type ShortOperator = FilterSimpleCondition['operator'];

type OperatorOption = {
  operator: ShortOperator;
  label: LiteralOperator;
  inputWidget?: React.ComponentType<any>;
};

export const DEFAULT_FILTER: FilterSimpleCondition = { column: '', value: '', operator: 'eq' };

const nullOperators: Readonly<OperatorOption[]> = [
  { operator: 'isnull', label: 'is null' },
  { operator: 'notnull', label: 'is not null' },
];

const baseOperators: Readonly<OperatorOption[]> = [
  { operator: 'eq', label: 'equals', inputWidget: InputTextWidget },
  { operator: 'ne', label: "doesn't equal", inputWidget: InputTextWidget },
  { operator: 'gt', label: 'is greater than', inputWidget: InputTextWidget },
  { operator: 'ge', label: 'is greater than or equal to', inputWidget: InputTextWidget },
  { operator: 'lt', label: 'is less than', inputWidget: InputTextWidget },
  { operator: 'le', label: 'is less than or equal to', inputWidget: InputTextWidget },
  { operator: 'in', label: 'is one of', inputWidget: MultiInputTextWidget },
  { operator: 'nin', label: 'is not one of', inputWidget: MultiInputTextWidget },
  { operator: 'matches', label: 'matches pattern', inputWidget: InputTextWidget },
  { operator: 'notmatches', label: "doesn't match pattern", inputWidget: InputTextWidget },
  ...nullOperators,
];

const dateOperators: Readonly<OperatorOption[]> = [
  { operator: 'from', label: 'starting in/on', inputWidget: NewDateInput },
  { operator: 'until', label: 'ending in/on', inputWidget: NewDateInput },
  ...nullOperators,
];

interface FilterSimpleConditionWidgetProps {
    value?: FilterSimpleCondition;
    columnNamesProp?: string[];
    dataPath?: string;
    errors?: any[]; // ErrorObject[]
    multiVariable?: boolean;
    columnTypes?: ColumnTypeMapping;
    availableVariables?: VariablesBucket;
    variableDelimiters?: VariableDelimiters;
    trustedVariableDelimiters?: VariableDelimiters;
    hideColumnVariables?: boolean;
    onChange: (val: FilterSimpleCondition) => void;
    onSetSelectedColumns?: (col: { column: string }) => void;
}

export default function FilterSimpleConditionWidget({
    value = { ...DEFAULT_FILTER },
    columnNamesProp = [],
    dataPath = '',
    errors = [],
    multiVariable = true,
    columnTypes = {},
    availableVariables,
    variableDelimiters,
    trustedVariableDelimiters,
    hideColumnVariables,
    onChange,
    onSetSelectedColumns,
}: FilterSimpleConditionWidgetProps) {

    const columnNames = columnNamesProp ?? [];
    const availableVariablesForInputWidget = availableVariables;

    const hasDateSelectedColumn = useMemo(() => {
        return columnTypes[value.column] === 'date';
    }, [columnTypes, value.column]);

    const availableOperators = useMemo(() => {
        if (hasDateSelectedColumn) {
            return dateOperators;
        }
        return baseOperators;
    }, [hasDateSelectedColumn]);

    const operator = useMemo(() => {
        return availableOperators.find((d) => d.operator === value.operator) ?? availableOperators[0];
    }, [availableOperators, value.operator]);

    const placeholder = useMemo(() => {
        if (value.operator === 'matches' || value.operator === 'notmatches') {
            return 'Enter a regex, e.g. "[Ss]ales"';
        }
        return 'Enter a value';
    }, [value.operator]);

    const InputWidget = operator.inputWidget;

    const updateStepOperator = (newOperator: OperatorOption) => {
        const updatedValue = { ...value };
        updatedValue.operator = newOperator.operator;

        if (updatedValue.operator === 'in' || updatedValue.operator === 'nin') {
             // @ts-ignore
            updatedValue.value = keepCurrentValueIfArrayType(updatedValue.value, []);
        } else if (updatedValue.operator === 'isnull' || updatedValue.operator === 'notnull') {
             // @ts-ignore
            updatedValue.value = null;
        } else if (hasDateSelectedColumn) {
             // @ts-ignore
            updatedValue.value = keepCurrentValueIfCompatibleRelativeDate(updatedValue.value, '');
        } else {
             // @ts-ignore
            updatedValue.value = keepCurrentValueIfCompatibleType(updatedValue.value, '');
        }
        onChange(updatedValue);
    };

    // Initialization logic
    useEffect(() => {
         if (isEqual(value, DEFAULT_FILTER)) {
            // No op
         } else if (hasDateSelectedColumn) {
             // Logic to update invalid date operator
             const retrieveOperatorOption = (op: string) => availableOperators.find((o) => o.operator === op);
             if (!retrieveOperatorOption(value.operator)) {
                  let newOperator: ShortOperator = 'eq'; // Default fallback
                   switch (value.operator) {
                    case 'lt':
                    case 'le':
                      newOperator = 'until';
                      break;
                    case 'gt':
                    case 'ge':
                      newOperator = 'from';
                      break;
                    case 'from':
                      newOperator = 'ge';
                      break;
                    case 'until':
                      newOperator = 'le';
                      break;
                  }
                  const newOpOption = retrieveOperatorOption(newOperator) ?? operator;
                  updateStepOperator(newOpOption);
             }
         }
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [hasDateSelectedColumn]); // Only run when date status changes or mount. But careful with mount.

    // Watch for column type change to reset values
    const prevHasDateSelectedColumn = useRef(hasDateSelectedColumn);
    useEffect(() => {
        if (prevHasDateSelectedColumn.current !== hasDateSelectedColumn) {
             // verifyIfValueIsStillValid
             updateStepOperator(operator);
             prevHasDateSelectedColumn.current = hasDateSelectedColumn;
        }
    // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [hasDateSelectedColumn, operator]); // We deliberately exclude updateStepOperator/value to avoid loops


    const updateStepValue = (newVal: any) => {
        const updatedValue = { ...value };
        updatedValue.value = newVal;
        onChange(updatedValue);
    };

    const updateStepColumn = (newValue: string) => {
        const updatedValue = { ...value };
        updatedValue.column = newValue;
        if (onSetSelectedColumns) {
            onSetSelectedColumns({ column: updatedValue.column });
        }
        onChange(updatedValue);
    };

    return (
        <div className={styles['filter-form-simple-condition__container']}>
            <div className={styles['filter-form-simple-condition-column-input']} data-cy="weaverbird-filter-form-column-input">
                <AutocompleteWidget
                    className="columnInput"
                    value={value.column}
                    availableVariables={hideColumnVariables ? undefined : availableVariables}
                    variableDelimiters={hideColumnVariables ? undefined : variableDelimiters}
                    trustedVariableDelimiters={hideColumnVariables ? undefined : trustedVariableDelimiters}
                    options={columnNames}
                    onChange={updateStepColumn}
                    placeholder="Column"
                    dataPath={`${dataPath}.column`}
                    errors={errors}
                    allowCustom={true}
                />
            </div>
            <div className={styles['filter-form-simple-condition-operator-input']} data-cy="weaverbird-filter-form-operator-input">
                <AutocompleteWidget
                     className="filterOperator"
                     value={operator.label} // Display label
                     trackBy="operator"
                     label="label"
                     onChange={(selected: any) => {
                         // Autocomplete might return string or object
                         if (typeof selected === 'string') {
                              const op = availableOperators.find(o => o.label === selected);
                              if (op) updateStepOperator(op);
                         } else if (selected && selected.operator) {
                              updateStepOperator(selected);
                         }
                     }}
                     options={availableOperators}
                     placeholder="Filter operator"
                />
            </div>
            {InputWidget && (
                <div className={styles['filter-form-simple-condition-column-input']}>
                <InputWidget
                    className="filterValue"
                    // data-cy="weaverbird-filter-form-filter-value"
                    multiVariable={multiVariable}
                    value={value.value}
                    availableVariables={availableVariablesForInputWidget}
                    variableDelimiters={variableDelimiters}
                    trustedVariableDelimiters={trustedVariableDelimiters}
                    placeholder={placeholder}
                    dataPath={`${dataPath}.value`}
                    errors={errors}
                    onChange={updateStepValue}
                />
                </div>
            )}
        </div>
    );
}
