// src/components/stepforms/widgets/List.vue
<template>
  <div class="widget-list__container" :class="toggleClassErrorWarning">
    <label v-if="name">{{ name }}</label>
    <div class="widget-list__body">
      <div class="widget-list__child" v-for="(child, index) in children" :key="index">
        <span class="widget-list__component-sep" v-if="index > 0 && separatorLabel">{{
          separatorLabel
        }}</span>
        <div
          class="widget-list__component"
          :class="{ 'widget-list__component--colored': !unstyledItems }"
        >
          <component
            :is="widget"
            v-bind="componentProps"
            :value="child.value"
            :options="options"
            :available-variables="availableVariables"
            :variable-delimiters="variableDelimiters"
            @input="updateChildValue($event, index)"
            :data-path="`${dataPath}[${index}]`"
            :errors="errors"
          />
        </div>
        <div class="widget-list__icon" v-if="child.isRemovable" @click="removeChild(index)">
          <FAIcon icon="far trash-alt" />
        </div>
      </div>
      <div v-if="messageError" class="field__msg-error">
        <FAIcon icon="exclamation-circle" />
        {{ messageError }}
      </div>
      <button v-if="!automaticNewField" class="widget-list__add-fieldset" @click="addFieldSet">
        <FAIcon icon="plus-circle" />
        {{ addFieldName }}
      </button>
    </div>
  </div>
</template>

<script lang="ts">
import { ErrorObject } from 'ajv';
import _ from 'lodash';
import { VueConstructor } from 'vue';
import { Component, Mixins, Prop, Vue } from 'vue-property-decorator';

import FAIcon from '@/components/FAIcon.vue';
import InputTextWidget from '@/components/stepforms/widgets/InputText.vue';
import { TotalDimension } from '@/lib/steps.ts';
import { VariableDelimiters, VariablesBucket } from '@/lib/variables';

import FormWidget from './FormWidget.vue';

type Field = {
  name: string;
  label?: string;
  value: any;
};

type RepeatableField = Field[];

@Component({
  name: 'list-widget',
  components: {
    FAIcon,
  },
})
export default class ListWidget extends Mixins(FormWidget) {
  @Prop({ type: String, default: '' })
  addFieldName!: string;

  @Prop({ type: Object, default: () => {} })
  componentProps!: object;

  @Prop({ type: String, default: '' })
  name!: string;

  @Prop({ type: String, default: null })
  separatorLabel!: string;

  @Prop({ type: Array, default: () => [] })
  value!: any[];

  @Prop({ type: Array, default: () => [] })
  options!: string[];

  @Prop({
    type: Function,
    default: InputTextWidget,
  })
  widget!: VueConstructor<Vue>;

  @Prop({ type: Boolean, default: true })
  automaticNewField!: boolean;

  @Prop({ default: null })
  defaultItem!: string | RepeatableField | TotalDimension;

  @Prop({ type: Array, default: () => [] })
  errors!: ErrorObject[];

  @Prop({ default: null })
  dataPath!: string;

  @Prop()
  availableVariables?: VariablesBucket;

  @Prop()
  variableDelimiters?: VariableDelimiters;

  // Remove gray box and padding around list elements
  @Prop({ type: Boolean, default: false })
  unstyledItems!: boolean;

  get children() {
    const valueCopy = [...this.value];
    if (this.automaticNewField) {
      valueCopy.push(this.defaultChildValue);
    }
    return valueCopy.map(value => ({
      isRemovable: valueCopy.length !== 1,
      value,
    }));
  }

  get defaultChildValue() {
    if (this.defaultItem) {
      return this.defaultItem;
    }
    if (this.widget === InputTextWidget) {
      return '';
    } else {
      return [];
    }
  }

  addFieldSet() {
    this.updateValue([...this.value, _.cloneDeep(this.defaultChildValue)]);
  }

  removeChild(index: number) {
    const newValue = [...this.value];
    newValue.splice(index, 1);
    this.updateValue(newValue);
  }

  updateChildValue(childValue: any, index: number) {
    const newValue = [...this.value];
    if (this.value.length < index) {
      newValue.push(childValue);
    } else {
      newValue[index] = childValue;
    }
    this.updateValue(newValue);
  }

  updateValue(newValue: Record<string, any>[]) {
    this.$emit('input', newValue);
  }
}
</script>
<style lang="scss" scoped>
@import '../../../styles/_variables';
::v-deep .fa-plus-circle {
  color: $active-color;
}

.widget-list__container {
  @extend %form-widget__container;
  ::v-deep.multiselect__tags {
    @extend %form-widget__field;
    background: #fff;
  }
}

.widget-list__container label {
  @extend %form-widget__label;
}

.widget-list__body {
  background: none;
  width: 100%;
  display: flex;
  flex-direction: column;
  padding: 0;
}

.widget-list__child {
  width: 100%;
  padding-right: 15px;
  position: relative;
  margin-bottom: 10px;
  display: flex;
  align-items: center;
}

.widget-list__component {
  width: 98%;

  ::v-deep label {
    width: 40%;
  }

  ::v-deep label + div {
    width: 60%;
  }
}

.widget-list__component--colored {
  background-color: #f8f8f8;
  padding: 8px 8px 0;
}

.widget-list__component-sep {
  font-size: 14px;
}

.widget-list__add-fieldset {
  @extend %button-default;
  align-self: center;
  background-color: #f8f8f8;
  border: 1px dashed $active-color;
  color: $active-color;
  font-weight: 500;
  width: 250px;
}

.widget-list__icon {
  margin-top: 8px;
  position: absolute;
  right: 0;
  top: calc(50% - 16px);
  cursor: pointer;
}
</style>
<style lang="scss">
.widget-list__container .widget-autocomplete__container {
  align-items: center;
  flex-direction: row;
  margin-bottom: 8px;
  flex-wrap: wrap;
}
.widget-list__container .widget-autocomplete__label {
  margin-bottom: 0px;
  width: 40%;
}
</style>

// next-ui/components/stepforms/widgets/List.tsx
// Placeholder for ListWidget
// This component manages a list of items using a dynamic component (passed as prop).
// In React, we pass the component class/function as a prop.

import React from 'react';
import _ from 'lodash';
import classNames from 'classnames';

import FAIcon from '@/components/FAIcon';
import { useFormWidget } from './FormWidget';
import InputTextWidget from './InputText'; // Default widget

import styles from './List.module.scss';
import formStyles from './FormWidget.module.scss';

interface ListWidgetProps {
  name?: string;
  addFieldName?: string;
  separatorLabel?: string;
  value?: any[];
  options?: any[]; // for child widgets
  widget?: React.ComponentType<any>; // React Component
  automaticNewField?: boolean; // If true, always shows an empty field at the end? Vue logic: "if automaticNewField, valueCopy.push(defaultChildValue)"
  defaultItem?: any;
  errors?: any[];
  dataPath?: string;
  availableVariables?: any;
  variableDelimiters?: any;
  trustedVariableDelimiters?: any;
  unstyledItems?: boolean;
  columnNames?: string[];
  selectedColumns?: string[];
  componentProps?: object;
  onChange: (val: any[]) => void;
  onSetSelectedColumns?: (val: any) => void;
  className?: string;
}

export default function ListWidget({
  name,
  addFieldName = 'Add',
  separatorLabel,
  value = [],
  options = [],
  widget: Widget = InputTextWidget, // Renaming to capitalize for JSX
  automaticNewField = true,
  defaultItem,
  errors,
  dataPath,
  availableVariables,
  variableDelimiters,
  trustedVariableDelimiters,
  unstyledItems = false,
  columnNames,
  selectedColumns,
  componentProps = {},
  onChange,
  onSetSelectedColumns,
  className
}: ListWidgetProps) {

  const { messageError, toggleClassErrorWarning } = useFormWidget({ dataPath, errors });

  // Default value logic
  const getDefaultChildValue = () => {
    if (defaultItem !== undefined && defaultItem !== null) {
      return defaultItem;
    }
    // Simple check if widget is InputTextWidget?
    // In React checking component identity is tricky if wrapped.
    // Assuming empty string is safe default for text, or empty array/object.
    return '';
  };

  const defaultChildValue = getDefaultChildValue();

  const handleUpdate = (newValue: any[]) => {
      onChange(newValue);
  };

  const children = (() => {
      const valueCopy = [...value];
      // Note: In Vue, computed property 'children' added a dummy item if automaticNewField is true.
      // But it didn't emit it.
      // And the loop rendered these children.
      if (automaticNewField) {
          valueCopy.push(defaultChildValue);
      }
      return valueCopy.map((val, idx) => ({
          isRemovable: !automaticNewField || valueCopy.length !== 1,
          value: val,
          originalIndex: idx
          // If automaticNewField is true, the last item is a "phantom" item.
          // If modified, it should likely be added to real value?
          // Vue: "updateChildValue" -> "if value.length < index ... push"
      }));
  })();

  const removeChild = (index: number) => {
      const newValue = [...value];
      newValue.splice(index, 1);
      handleUpdate(newValue);
  };

  const updateChildValue = (childValue: any, index: number) => {
      const newValue = [...value];
      if (index >= newValue.length) {
          newValue.push(childValue);
      } else {
          newValue[index] = childValue;
      }
      handleUpdate(newValue);
  };

  const addFieldSet = () => {
      handleUpdate([...value, _.cloneDeep(defaultChildValue)]);
  };

  return (
    <div className={classNames(styles['widget-list__container'], toggleClassErrorWarning, className)}>
      {name && <label className={styles['widget-list__label']}>{name}</label>}
      <div className={styles['widget-list__body']}>
        {children.map((child, index) => {
            const isLastPhantom = automaticNewField && index === children.length - 1;

            return (
              <div className={styles['widget-list__child']} key={index}>
                {index > 0 && separatorLabel && (
                    <span className={styles['widget-list__component-sep']}>{separatorLabel}</span>
                )}

                <div className={classNames(styles['widget-list__component'], {
                    [styles['widget-list__component--colored']]: !unstyledItems
                })}>
                    <Widget
                        {...componentProps}
                        value={child.value}
                        options={options}
                        availableVariables={availableVariables}
                        variableDelimiters={variableDelimiters}
                        trustedVariableDelimiters={trustedVariableDelimiters}
                        dataPath={`${dataPath || ''}.${index}`}
                        errors={errors}
                        columnNames={columnNames}
                        selectedColumns={selectedColumns}
                        onChange={(v: any) => updateChildValue(v, index)}
                        onSetSelectedColumns={onSetSelectedColumns}
                    />
                </div>

                {child.isRemovable && !isLastPhantom && (
                    <div className={styles['widget-list__icon']} onClick={() => removeChild(index)}>
                        <FAIcon icon="far trash-alt" />
                    </div>
                )}
              </div>
            );
        })}

        {messageError && (
            <div className={formStyles['field__msg-error']}>
            <FAIcon icon="exclamation-circle" />
            {messageError}
            </div>
        )}

        {!automaticNewField && (
            <button className={styles['widget-list__add-fieldset']} onClick={addFieldSet}>
                <FAIcon className={styles['widget-list__add-fieldset-icon']} icon="plus" /> {/* plus-circle in vue, check FA map */}
                {addFieldName}
            </button>
        )}
      </div>
    </div>
  );
}
