// next-ui/components/FilterEditor.tsx
import React, { useMemo } from 'react';
import { ErrorObject } from 'ajv';

import ConditionsEditor from '@/components/ConditionsEditor/ConditionsEditor';
import { AbstractFilterTree } from '@/components/ConditionsEditor/tree-types';
import {
  buildConditionsEditorTree,
  buildFilterStepTree,
  castFilterStepTreeValue,
} from '@/components/stepforms/convert-filter-step-tree';
import FilterSimpleConditionWidget, {
  DEFAULT_FILTER,
} from '@/components/stepforms/widgets/FilterSimpleCondition';
import { ColumnTypeMapping } from '@/lib/dataset';
import { FilterCondition, FilterSimpleCondition } from '@/lib/steps';
import { VariableDelimiters, VariablesBucket } from '@/lib/variables';

interface FilterEditorProps {
  filterTree?: FilterCondition;
  columnTypes?: ColumnTypeMapping;
  availableVariables?: VariablesBucket;
  variableDelimiters?: VariableDelimiters;
  trustedVariableDelimiters?: VariableDelimiters;
  hideColumnVariables?: boolean;
  multiVariable?: boolean;
  errors?: ErrorObject[];
  onFilterTreeUpdated: (newTree: FilterCondition) => void;
  onSetSelectColumns?: (columns: { column: string }) => void;
}

export default function FilterEditor({
  filterTree = { column: '', value: '', operator: 'eq' },
  columnTypes = {},
  availableVariables,
  variableDelimiters,
  trustedVariableDelimiters,
  hideColumnVariables,
  multiVariable = true,
  errors = [],
  onFilterTreeUpdated,
  onSetSelectColumns,
}: FilterEditorProps) {

  const defaultValue = DEFAULT_FILTER;

  const conditionsTree = useMemo(() => {
    return buildConditionsEditorTree(castFilterStepTreeValue(filterTree, columnTypes));
  }, [filterTree, columnTypes]);

  const updateFilterTree = (newConditionsTree: AbstractFilterTree) => {
    const newFilterTree = buildFilterStepTree(newConditionsTree);
    // Cast back to FilterCondition because buildFilterStepTree returns object
    onFilterTreeUpdated(newFilterTree as FilterCondition);
  };

  return (
    <div className="filter-editor">
      <ConditionsEditor
        conditionsTree={conditionsTree}
        onConditionsTreeUpdated={updateFilterTree}
        defaultValue={defaultValue}
        renderCondition={({ condition, updateCondition, dataPath }) => (
            <FilterSimpleConditionWidget
                value={condition || undefined}
                onChange={updateCondition}
                columnNamesProp={Object.keys(columnTypes)}
                availableVariables={availableVariables}
                variableDelimiters={variableDelimiters}
                trustedVariableDelimiters={trustedVariableDelimiters}
                hideColumnVariables={hideColumnVariables}
                dataPath={dataPath}
                errors={errors}
                multiVariable={multiVariable}
                columnTypes={columnTypes}
                onSetSelectedColumns={onSetSelectColumns}
            />
        )}
      />
    </div>
  );
}

// ui/src/components/FilterEditor.vue
<template>
  <div class="filter-editor">
    <ConditionsEditor
      :conditions-tree="conditionsTree"
      @conditionsTreeUpdated="updateFilterTree"
      :defaultValue="defaultValue"
    >
      <template v-slot:default="slotProps">
        <FilterSimpleConditionWidget
          :value="slotProps.condition || undefined"
          @input="slotProps.updateCondition"
          :columnNamesProp="Object.keys(columnTypes)"
          :available-variables="availableVariables"
          :variable-delimiters="variableDelimiters"
          :trusted-variable-delimiters="trustedVariableDelimiters"
          :hideColumnVariables="hideColumnVariables"
          :data-path="slotProps.dataPath"
          :errors="errors"
          :multi-variable="multiVariable"
          :columnTypes="columnTypes"
          @setSelectedColumns="$emit('setSelectColumns', $event)"
        />
      </template>
    </ConditionsEditor>
  </div>
</template>

<script lang="ts">
import type { ErrorObject } from 'ajv';
import { defineComponent, PropType } from 'vue';

import ConditionsEditor from '@/components/ConditionsEditor/ConditionsEditor.vue';
import type { AbstractFilterTree } from '@/components/ConditionsEditor/tree-types';
import {
  buildConditionsEditorTree,
  buildFilterStepTree,
  castFilterStepTreeValue,
} from '@/components/stepforms/convert-filter-step-tree';
import FilterSimpleConditionWidget, {
  DEFAULT_FILTER,
} from '@/components/stepforms/widgets/FilterSimpleCondition.vue';
import type { ColumnTypeMapping } from '@/lib/dataset';
import type { FilterCondition } from '@/lib/steps';
import type { VariableDelimiters, VariablesBucket } from '@/lib/variables';

export default defineComponent({
  name: 'filter-editor',

  components: {
    ConditionsEditor,
    FilterSimpleConditionWidget,
  },

  props: {
    filterTree: {
      type: Object as PropType<FilterCondition>,
      default: () => ({ column: '', value: '', operator: 'eq' }),
    },
    columnTypes: {
      type: Object as PropType<ColumnTypeMapping>,
      default: () => ({}),
    },
    availableVariables: {
      type: Object as PropType<VariablesBucket>,
    },
    variableDelimiters: {
      type: Object as PropType<VariableDelimiters>,
    },
    trustedVariableDelimiters: {
      type: Object as PropType<VariableDelimiters>,
    },
    hideColumnVariables: {
      type: Boolean,
    },
    multiVariable: {
      type: Boolean,
      default: true,
    },
    errors: {
      type: Array as PropType<ErrorObject[]>,
      default: () => [],
    },
  },

  data() {
    return {
      defaultValue: DEFAULT_FILTER,
    };
  },

  computed: {
    conditionsTree() {
      return buildConditionsEditorTree(castFilterStepTreeValue(this.filterTree, this.columnTypes));
    },
  },

  methods: {
    updateFilterTree(newConditionsTree: AbstractFilterTree) {
      const newFilterTree = buildFilterStepTree(newConditionsTree);
      this.$emit('filterTreeUpdated', newFilterTree);
    },
  },
});
</script>
