// next-ui/components/Popover.tsx
import React, { useEffect, useRef, useState, useCallback, ReactNode, CSSProperties } from 'react';
import { createPortal } from 'react-dom';
import _ from 'lodash';
import classNames from 'classnames';

import { Alignment } from '@/components/constants';
import * as DOMUtil from '@/components/domutil';
import styles from './Popover.module.scss';

interface PopoverProps {
  visible: boolean;
  align?: Alignment;
  bottom?: boolean;
  forcePositionUpdate?: number;
  alwaysOpened?: boolean;
  shouldCalculateHeight?: boolean;
  children: ReactNode;
  onClosed?: () => void;
  /**
   * Optional container to mount the popover into.
   * Defaults to document.body if not provided.
   * Note: In Next.js/SSR, document.body is only available after mount.
   */
  container?: Element;
}

export default function Popover({
  visible,
  align = Alignment.Center,
  bottom = false,
  forcePositionUpdate = 0,
  alwaysOpened = false,
  shouldCalculateHeight = false,
  children,
  onClosed,
  container,
}: PopoverProps) {
  const popoverRef = useRef<HTMLDivElement>(null);
  const [elementStyle, setElementStyle] = useState<CSSProperties>({});
  const [parent, setParent] = useState<HTMLElement | null>(null);
  const [parents, setParents] = useState<HTMLElement[]>([]);

  // We need to keep track of the original parent to anchor the popover
  // But we need to render the popover in the portal (body or container)

  // To simulate the Vue behavior where it's inserted in place and then moved,
  // we can use a "placeholder" ref to find the parent.
  const placeholderRef = useRef<HTMLDivElement>(null);

  // Determine the target container
  const [targetContainer, setTargetContainer] = useState<Element | null>(null);

  useEffect(() => {
    if (typeof document !== 'undefined') {
        setTargetContainer(container || document.body);
    }
  }, [container]);

  const updatePosition = useCallback(
    _.throttle(() => {
      if (!parent || !popoverRef.current || !targetContainer) return;

      const el = popoverRef.current;

      const positionContext = {
        body: targetContainer.getBoundingClientRect(),
        parent: parent.getBoundingClientRect(),
        element: el,
        window: window,
      };

      // Set alignment
      // Use type assertion to avoid @ts-ignore. DOMUtil functions return objects that match partial CSS properties.
      const computedStyle = DOMUtil.align(align, positionContext) as Record<string, string | number>;
      computedStyle.top = DOMUtil.computeTop(bottom, positionContext);
      if (shouldCalculateHeight) {
        computedStyle.height = DOMUtil.computeHeight(bottom, positionContext) as number;
      }

      // Convert to CSS properties with px
      const newStyle: CSSProperties = {};
      Object.entries(computedStyle).forEach(([k, v]) => {
          if (v !== undefined) {
             // @ts-ignore: dynamic assignment to CSSProperties
             newStyle[k as any] = `${v}px`;
          }
      });
      setElementStyle(newStyle);

    }, 16),
    [align, bottom, shouldCalculateHeight, parent, targetContainer]
  );

  // Initialize parent and parents list
  useEffect(() => {
    if (placeholderRef.current) {
        const foundParent = placeholderRef.current.parentElement;
        setParent(foundParent);

        if (foundParent && targetContainer) {
             // Get all scrollable parents
             let p = foundParent;
             const newParents: HTMLElement[] = [];
             while (p && p !== targetContainer && p !== document.body) { // Safe check
                newParents.push(p);
                if (p.parentElement) {
                    p = p.parentElement;
                } else {
                    break;
                }
             }
             setParents(newParents);
        }
    }
  }, [targetContainer]);

  // Setup listeners
  useEffect(() => {
    if (!visible || alwaysOpened || !targetContainer || !parent) return;

    updatePosition(); // Initial position update

    const clickListener = () => {
        if (onClosed) onClosed();
    };

    // In Vue: window.addEventListener('click', this.clickListener);
    // But we need to make sure we don't trigger it immediately if the click that opened it bubbles up?
    // In Vue they use @click.stop on the popover div.

    window.addEventListener('click', clickListener);
    window.addEventListener('orientationchange', updatePosition);
    window.addEventListener('resize', updatePosition);
    parents.forEach(p => p.addEventListener('scroll', updatePosition));

    return () => {
      window.removeEventListener('click', clickListener);
      window.removeEventListener('orientationchange', updatePosition);
      window.removeEventListener('resize', updatePosition);
      parents.forEach(p => p.removeEventListener('scroll', updatePosition));
    };
  }, [visible, alwaysOpened, targetContainer, parent, parents, updatePosition, onClosed]);


  // Watch forcePositionUpdate
  useEffect(() => {
      if (visible) updatePosition();
  }, [forcePositionUpdate, visible, updatePosition]);

  const handlePopoverClick = (e: React.MouseEvent) => {
      e.stopPropagation();
  };

  if (!targetContainer) return <div ref={placeholderRef} style={{ display: 'none' }} />;

  // If alwaysOpened, render in place (at placeholder location effectively, but we need to see how Vue did it)
  // Vue: if alwaysOpened, it doesn't move it to body. It stays where it is.
  if (alwaysOpened) {
      return (
        <div
          ref={popoverRef}
          className={classNames(styles['weaverbird-popover'], styles['weaverbird-popover--always-opened'], {
              [styles['weaverbird-popover--calculated-height']]: shouldCalculateHeight
          })}
          data-cy="weaverbird-popover"
          style={elementStyle}
          onClick={handlePopoverClick}
        >
          {children}
        </div>
      );
  }

  if (!visible) return <div ref={placeholderRef} style={{ display: 'none' }} />;

  // Render in portal
  return (
      <>
        <div ref={placeholderRef} style={{ display: 'none' }} />
        {createPortal(
            <div
                ref={popoverRef}
                className={classNames(styles['weaverbird-popover'], {
                    [styles['weaverbird-popover--calculated-height']]: shouldCalculateHeight
                })}
                data-cy="weaverbird-popover"
                style={elementStyle}
                onClick={handlePopoverClick}
            >
            {children}
            </div>,
            targetContainer
        )}
      </>
  );
}

// ui/src/components/Popover.vue
<template>
  <div
    class="weaverbird-popover"
    :class="{
      'weaverbird-popover--always-opened': alwaysOpened,
      'weaverbird-popover--calculated-height': shouldCalculateHeight,
    }"
    data-cy="weaverbird-popover"
    :style="elementStyle"
    @click.stop
  >
    <slot />
  </div>
</template>
<script lang="ts">
import _ from 'lodash';
import { defineComponent, PropType } from 'vue';

import { Alignment } from '@/components/constants';
import * as DOMUtil from '@/components/domutil';

/**
 * We use weak typing as it is used to define CSS rules
 * And that we're not forced to define all four properties
 */
interface ElementPosition {
  top?: string | number;
  bottom?: string | number;
  left?: string | number;
  right?: string | number;
  height?: string | number;
}

/**
@type {VueComponent}
@name Popover

@description
Implement a popover component
@params {Boolean} visible sets the popover visibility. If `true` the popover is mounted.

@params {String} [align = 'center'] sets the popover's default alignment:
  - possible values work like the text-align CSS property
  - justify adapts the popover to its parent (same width and horizontal position)

@params {Boolean} [bottom = false] sets the default position to below instead of above

@params {Boolean} [alwaysOpened = false] always displays the popover, and keep its content in the page flow rather than
in an floating element. Useful to create previews of configurable popovers. Make the prop `visible` effect-less.
*/
export default defineComponent({
  name: 'popover',
  
  inject: {
    weaverbirdPopoverContainer: {
      default: () => document.body
    }
  },
  
  props: {
    visible: {
      type: Boolean,
      required: true
    },
    align: {
      type: String as PropType<Alignment>,
      default: () => Alignment.Center,
      validator: (value: string) => Object.values(Alignment).includes(value as Alignment)
    },
    bottom: {
      type: Boolean,
      default: false
    },
    forcePositionUpdate: {
      type: Number,
      default: 0 // we increment the number each time we need the position to be updated
    },
    alwaysOpened: {
      type: Boolean,
      default: false
    },
    shouldCalculateHeight: {
      type: Boolean,
      default: false
    }
  },
  
  data() {
    return {
      elementStyle: {} as ElementPosition,
      parent: null as HTMLElement | null,
      element: null as HTMLElement | null,
      parents: [] as HTMLElement[],
      updatePositionListener: () => this.updatePosition(),
      clickListener: () => this.$emit('closed')
    };
  },
  
  watch: {
    visible: {
      async handler(visible: boolean) {
        if (this.alwaysOpened) {
          return;
        }

        if (!visible) {
          this.destroyPositioning();
        } else {
          this.setupPositioning();
        }
      }
    },
    forcePositionUpdate() {
      this.updatePosition();
    }
  },
  
  mounted() {
    if (this.alwaysOpened) {
      // Skip all the repositioning in the DOM
      return;
    }

    // Save original parent before moving into body to use its position
    this.parent = (this.$el as HTMLElement).parentElement;
    let { parent } = this;
    if (parent === null) {
      throw new Error('The popover has no parent!');
    }

    // Remove element from parent: it will be added to body when `setupPosition`
    parent.removeChild(this.$el as HTMLElement);

    // Get all scrollable parents
    const parents: HTMLElement[] = [];
    while (parent !== this.weaverbirdPopoverContainer) {
      parents.push(parent);
      if (parent.parentElement) {
        parent = parent.parentElement;
      } else {
        break;
      }
    }

    this.parents = parents;

    if (this.visible) {
      this.setupPositioning();
    }
  },
  
  beforeDestroy() {
    if (this.visible && !this.alwaysOpened) {
      this.destroyPositioning();
    }
  },
  
  methods: {
    setupPositioning() {
      this.weaverbirdPopoverContainer.appendChild(this.$el as HTMLElement);
      this.updatePosition();
      // Attach listeners
      window.addEventListener('click', this.clickListener);
      window.addEventListener('orientationchange', this.updatePositionListener);
      window.addEventListener('resize', this.updatePositionListener);
      for (const parent of this.parents) {
        parent.addEventListener('scroll', this.updatePositionListener);
      }
    },
    
    destroyPositioning() {
      // Cleanup listeners
      window.removeEventListener('click', this.clickListener);
      window.removeEventListener('orientationchange', this.updatePositionListener);
      window.removeEventListener('resize', this.updatePositionListener);
      for (const parent of this.parents) {
        parent.removeEventListener('scroll', this.updatePositionListener);
      }
      // Cleanup DOM
      if ((this.$el as HTMLElement).parentElement !== null) {
        return (this.$el as HTMLElement).parentElement?.removeChild(this.$el as HTMLElement);
      }
    },
    
    // Set the absolute position
    // Checks available space on screen for vertical positioning and alignment
    updatePosition: _.throttle(
      function (this: any) {
        if (this.parent === null) {
          return;
        }

        const positionContext = {
          body: this.weaverbirdPopoverContainer.getBoundingClientRect(),
          parent: this.parent.getBoundingClientRect(),
          element: this.$el,
          window,
        };
        // Set alignment
        const elementStyle: ElementPosition = DOMUtil.align(this.align, positionContext);
        elementStyle.top = DOMUtil.computeTop(this.bottom, positionContext);
        if (this.shouldCalculateHeight) {
          elementStyle.height = DOMUtil.computeHeight(this.bottom, positionContext);
        }
        // make sure to use `px` unit explicitly
        this.elementStyle = _.fromPairs(Object.entries(elementStyle).map(([k, v]) => [k, `${v}px`]));
      },
      // 60fps
      16
    )
  }
});
</script>
<style lang="scss" scoped>
.weaverbird-popover {
  font-family: 'Montserrat', sans-serif;
  position: absolute;
  visibility: visible;
  z-index: 2;
}
</style>
